### ISSUE TITLE
Missing some data in “affordance-language/data”

### ISSUE THREAD

**Issue by KennithLi** [Thaonguyen3095/affordance-language#1]
Hi, thank you for your pioneering work. I am interested in your work and trying to run your code. But I found that some data was missed in the “affordance-language/data” folder, like 'corpus-train.csv', 'corpus-test.csv', 'ycb-object-embedding.csv', 'vo_dict_verb.json'. I failed to run the whole project. So could you upload these data or update the codes?

Thank you for your attention!

**Comment by Thaonguyen3095** [comment]
Hi, I just uploaded the missing data files. Thank you for your interest in the project and for pointing out the missing files!
