### ISSUE TITLE
problem about Robot Demonstrations

### ISSUE THREAD

**Issue by rex131** [Thaonguyen3095/affordance-language#3]
i am running your code "eval.py" and i find it just can choose the right pictures in the input. i wanna reallize Robot Demonstrations  
which you mentioned in your papaer(The robot then grasps the observed object). how can i do? i want to check if there is any code about this?
it will be very kind of you to replying me. thank you for your time!

**Comment by Thaonguyen3095** [comment]
My apologies for the late reply, we used a system developed in our lab for the object grasping. You can find the paper and code for that [here](https://mattcorsaro1.github.io/2021/09/29/multimodalgrasping.html). Other off-the-shelf grasping algorithms could also be applied.
